version: '3.8'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx.Dockerfile
    restart: always
    volumes:
      - ./nginx/etc/conf.d:/etc/nginx/conf.d
      - ./backend:/var/www/app
    ports:
      - "80:80"

  backend:
    build:
      context: ./
      dockerfile: ./backend/dev.Dockerfile
    restart: always 
    volumes:
      - ./backend:/var/www/app

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/dev.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/app

  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/var/lib/postgresql:/var/lib/postgresql

  redis:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - "6379:6379"
