services:
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    restart: ${DOCKER_RESTART}
    volumes:
      - ./docker/nginx/etc/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - user_service

  user_service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_NAME: user_service
        PHP_VERSION: 8.3
    restart: ${DOCKER_RESTART}
    depends_on:
      - postgres
      - user_service_redis
      - rabbitmq
    volumes:
      - ./user_service:/var/www/app

  task_service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_NAME: task_service
        PHP_VERSION: 8.3
    restart: ${DOCKER_RESTART}
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./task_service:/var/www/app

  notification_service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_NAME: notification_service
        PHP_VERSION: 8.3
    restart: ${DOCKER_RESTART}
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - ./notification_service:/var/www/app

  file_service:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
      args:
        SERVICE_NAME: file_service
        PHP_VERSION: 8.3
    restart: ${DOCKER_RESTART}
    depends_on:
      - postgres
    volumes:
      - ./file_service:/var/www/app
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    restart: ${DOCKER_RESTART}
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/node_modules:/app/node_modules
      - /app/node_modules
      - /app/.next

  postgres:
    image: postgres:17.4-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./docker/postgres/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"

  user_service_redis:
    image: redis:7.4.2-alpine3.21
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:4.0.7-management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  mailhog:
    container_name: mailhog
    restart: ${DOCKER_RESTART}
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
      - "1025:1025"
