version: '3.8'

services:
  nginx:
    build:
      context: ./
      dockerfile: ./nginx.Dockerfile
    restart: always
    volumes:
      - ./backend/vendor:/var/www/app/storage
      - ./backend/vendor:/var/www/app/vendor
    ports:
      - "80:80"

  backend:
    build:
      context: ./
      dockerfile: ./backend/Dockerfile
    restart: always
    volumes:
      - ./backend/vendor:/var/www/app/storage
      - ./backend/vendor:/var/www/app/vendor

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    restart: always

  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./postgres/var/lib/postgresql:/var/lib/postgresql

  redis:
    image: redis:7.4.1-alpine
    restart: always

volumes:
  postgres_data:
