old_sound_rabbit_mq:
    connections:
        default:
            host: '%env(RABBITMQ_HOST)%'
            port: '%env(RABBITMQ_PORT)%'
            user: '%env(RABBITMQ_USER)%'
            password: '%env(RABBITMQ_PASSWORD)%'
            vhost: '/'
            lazy: false
            connection_timeout: 3
            read_write_timeout: 3
    producers:
        upload_task:
            connection: default
            exchange_options: { name: 'upload-task', type: fanout }
        delete_task:
            connection: default
            exchange_options: { name: 'delete-task', type: fanout }
    consumers:
        upload_user:
            connection: default
            exchange_options: { name: 'upload-user', type: fanout }
            queue_options: { name: 'task_service.user'}
            callback: App\Consumer\UserConsumer